### ISSUE TITLE
how to compile suitesparse by NDK?

### ISSUE THREAD

**Issue by jyzhong** [kiutao/suitespare_android_lib#1]
Hi, how to make this suitesparse ? i cann't do it success. I just run the two .sh file.
 ps: i try to compile suitesparse by NDK, but it tells me "couldn't link with cholomod“. i find your work, but i donn't know how to compile it. I wish get your reply, thanks!

**Comment by kiutao** [comment]
sorry for late replay. This is compiled by NDK.  u can find it under your Android Studio. git clone it and run sh ..if possible , can u provide more information? thanks.

**Comment by jyzhong** [comment]
i git clone it, then run sh using terminal. As a result, I get the following messages:CMake Error: The source directory "/home/slam/Documents/tool" does not appear to contain CMakeLists.txt. I find the .sh　files set the path of "android.toolchain.cmake"and "ndk-bundle".  Is this my issue?  but i couldn't find the relative path of those varible.

**Comment by kiutao** [comment]
cmake -DCMAKE_TOOLCHAIN_FILE=xx/android.toolchain.cmake -DANDROID_NDK=/home/pico/Android/Sdk/ndk-bundle -DANDROID_TOOLCHAIN="gcc" -DCMAKE_BUILD_TYPE=Release -DBUILD_ANDROID=TRUE -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DANDROID_ARM_NEON=TRUE  -DEIGEN3_INCLUDE_DIR="/usr/local/include/eigen3" -DEIGEN3_VERSION_OK=ON -DANDROID_DISABLE_FORMAT_STRING_CHECKS=TRUE -DSHARED="SHARED" .. && cmake --build .

**Comment by kiutao** [comment]
**export CLAPACKDIR={your clapack dir}**
cmake -DCMAKE_TOOLCHAIN_FILE=xx/android.toolchain.cmake -DANDROID_NDK=/home/pico/Android/Sdk/ndk-bundle -DANDROID_TOOLCHAIN="gcc" -DCMAKE_BUILD_TYPE=Release -DBUILD_ANDROID=TRUE -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DANDROID_ARM_NEON=TRUE  -DEIGEN3_INCLUDE_DIR="/usr/local/include/eigen3" -DEIGEN3_VERSION_OK=ON -DANDROID_DISABLE_FORMAT_STRING_CHECKS=TRUE -DSHARED="SHARED" .. && cmake --build .

**Comment by kiutao** [comment]
pls check your environment. this project just compile suitesparse to .so file.

**Comment by jyzhong** [comment]
i have android ndk,  do i need android-sdk?

**Comment by kiutao** [comment]
not necessary.

**Comment by jyzhong** [comment]
but i could find "xx/android.toolchain.cmake" and "ndk-bundle".

**Comment by jyzhong** [comment]
but i couldn't  find "xx/android.toolchain.cmake" and "ndk-bundle".

**Comment by kiutao** [comment]
nono that file should be : android.toolchain.cmake . if u not know how to , just  download android studio.

**Comment by jyzhong** [comment]
I will try to download android studio. Thanks.

**Comment by kiutao** [comment]
也可以去这里看看有无需要的。
https://developer.arm.com/tools-and-software/server-and-hpc/arm-architecture-tools/arm-performance-libraries
